# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1071, 807)
        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setGeometry(QtCore.QRect(240, -10, 771, 111))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_title.setObjectName("label_title")
        self.label_scope = QtWidgets.QLabel(Dialog)
        self.label_scope.setGeometry(QtCore.QRect(220, 70, 851, 91))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_scope.setFont(font)
        self.label_scope.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.label_scope.setObjectName("label_scope")
        self.label_copyright = QtWidgets.QLabel(Dialog)
        self.label_copyright.setGeometry(QtCore.QRect(350, 750, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_copyright.setFont(font)
        self.label_copyright.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_copyright.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_copyright.setObjectName("label_copyright")
        self.button_number = QtWidgets.QPushButton(Dialog)
        self.button_number.setGeometry(QtCore.QRect(960, 170, 101, 31))
        self.button_number.setObjectName("button_number")
        self.label_wzklogo = QtWidgets.QLabel(Dialog)
        self.label_wzklogo.setGeometry(QtCore.QRect(970, 730, 101, 81))
        self.label_wzklogo.setStyleSheet("background-image: url(:/b1/1.jpg);")
        self.label_wzklogo.setText("")
        self.label_wzklogo.setObjectName("label_wzklogo")
        self.label_redbg = QtWidgets.QLabel(Dialog)
        self.label_redbg.setGeometry(QtCore.QRect(0, 0, 1071, 91))
        self.label_redbg.setStyleSheet("background-color: rgb(191, 3, 6);")
        self.label_redbg.setText("")
        self.label_redbg.setObjectName("label_redbg")
        self.label_greybg = QtWidgets.QLabel(Dialog)
        self.label_greybg.setGeometry(QtCore.QRect(0, 90, 1071, 51))
        self.label_greybg.setStyleSheet("background-color: rgb(160, 160, 160);")
        self.label_greybg.setText("")
        self.label_greybg.setObjectName("label_greybg")
        self.label_blackbg = QtWidgets.QLabel(Dialog)
        self.label_blackbg.setGeometry(QtCore.QRect(0, 730, 1071, 121))
        self.label_blackbg.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_blackbg.setText("")
        self.label_blackbg.setObjectName("label_blackbg")
        self.label_lightgrey = QtWidgets.QLabel(Dialog)
        self.label_lightgrey.setGeometry(QtCore.QRect(0, 140, 9, 21))
        self.label_lightgrey.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.label_lightgrey.setText("")
        self.label_lightgrey.setObjectName("label_lightgrey")
        self.line_input = QtWidgets.QLineEdit(Dialog)
        self.line_input.setGeometry(QtCore.QRect(210, 170, 451, 31))
        self.line_input.setStyleSheet("color: rgb(0, 0, 0);")
        self.line_input.setText("")
        self.line_input.setObjectName("line_input")
        self.line_input_2 = QtWidgets.QLineEdit(Dialog)
        self.line_input_2.setGeometry(QtCore.QRect(20, 170, 171, 31))
        self.line_input_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.line_input_2.setText("")
        self.line_input_2.setObjectName("line_input_2")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(680, 170, 261, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(0, 220, 1071, 451))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(15)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.button_author_rank = QtWidgets.QPushButton(Dialog)
        self.button_author_rank.setGeometry(QtCore.QRect(380, 680, 151, 34))
        self.button_author_rank.setObjectName("button_author_rank")
        self.button_subject_rank = QtWidgets.QPushButton(Dialog)
        self.button_subject_rank.setGeometry(QtCore.QRect(570, 680, 151, 34))
        self.button_subject_rank.setObjectName("button_subject_rank")
        self.label_lightgrey.raise_()
        self.label_blackbg.raise_()
        self.label_greybg.raise_()
        self.label_redbg.raise_()
        self.label_title.raise_()
        self.label_scope.raise_()
        self.label_copyright.raise_()
        self.button_number.raise_()
        self.label_wzklogo.raise_()
        self.line_input.raise_()
        self.line_input_2.raise_()
        self.comboBox.raise_()
        self.textBrowser.raise_()
        self.button_author_rank.raise_()
        self.button_subject_rank.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.line_input_2, self.line_input)
        Dialog.setTabOrder(self.line_input, self.comboBox)
        Dialog.setTabOrder(self.comboBox, self.button_number)
        Dialog.setTabOrder(self.button_number, self.textBrowser)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Arxiv Paper Retriever"))
        self.label_title.setText(_translate("Dialog", "Arxiv Paper Retriever"))
        self.label_scope.setText(_translate("Dialog", "Scope: Computer Science, 2019  (51405 papers in total)"))
        self.label_copyright.setText(_translate("Dialog", "Copyright@wzk 1999-?  All rights reserved"))
        self.button_number.setText(_translate("Dialog", "Search"))
        self.line_input.setPlaceholderText(_translate("Dialog", "Arxiv number / Title"))
        self.line_input_2.setPlaceholderText(_translate("Dialog", "Subject (optional)"))
        self.comboBox.setItemText(0, _translate("Dialog", "Title (regular expression)"))
        self.comboBox.setItemText(1, _translate("Dialog", "Title (precise)"))
        self.comboBox.setItemText(2, _translate("Dialog", "Arxiv Number"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Adobe Arabic\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.button_author_rank.setText(_translate("Dialog", "Author Rank"))
        self.button_subject_rank.setText(_translate("Dialog", "Subject Rank"))

